/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author lerinha
 */
public class TelaPrincipalSDI extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalMDI
     */
    public TelaPrincipalSDI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jFrame2 = new javax.swing.JFrame();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        jMenu17 = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenu20 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenu24 = new javax.swing.JMenu();
        jMenu25 = new javax.swing.JMenu();
        jMenu26 = new javax.swing.JMenu();
        jFrame3 = new javax.swing.JFrame();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu27 = new javax.swing.JMenu();
        jMenu28 = new javax.swing.JMenu();
        jMenu29 = new javax.swing.JMenu();
        jMenu30 = new javax.swing.JMenu();
        jMenu31 = new javax.swing.JMenu();
        jMenu32 = new javax.swing.JMenu();
        jMenu33 = new javax.swing.JMenu();
        jMenu34 = new javax.swing.JMenu();
        jMenu35 = new javax.swing.JMenu();
        jMenu36 = new javax.swing.JMenu();
        jMenu37 = new javax.swing.JMenu();
        jMenu38 = new javax.swing.JMenu();
        jMenu39 = new javax.swing.JMenu();
        Desktop1 = new javax.swing.JDesktopPane();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu40 = new javax.swing.JMenu();
        jMenu44 = new javax.swing.JMenu();
        jMenu41 = new javax.swing.JMenu();
        fCadastrar = new javax.swing.JMenu();
        jMenu46 = new javax.swing.JMenu();
        jMenu47 = new javax.swing.JMenu();
        jMenu48 = new javax.swing.JMenu();
        jMenu42 = new javax.swing.JMenu();
        jMenu49 = new javax.swing.JMenu();
        jMenu50 = new javax.swing.JMenu();
        jMenu51 = new javax.swing.JMenu();
        jMenu52 = new javax.swing.JMenu();
        jMenu43 = new javax.swing.JMenu();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\Archivos_25593.png")); // NOI18N
        jMenu1.setText("Arquivos");

        jMenu5.setText("Sair");
        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\bootloader_users_person_people_6080.png")); // NOI18N
        jMenu2.setText("Usuários");

        jMenu6.setText("Cadastrar");
        jMenu2.add(jMenu6);

        jMenu7.setText("Alterar");
        jMenu2.add(jMenu7);

        jMenu8.setText("Excluir");
        jMenu2.add(jMenu8);

        jMenu9.setText("Pesquisar");
        jMenu2.add(jMenu9);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\userrating-115845_115824.png")); // NOI18N
        jMenu3.setText("Clientes");

        jMenu10.setText("Cadastrar");
        jMenu3.add(jMenu10);

        jMenu11.setText("Alterar");
        jMenu3.add(jMenu11);

        jMenu12.setText("Excluir");
        jMenu3.add(jMenu12);

        jMenu13.setText("Pesquisar");
        jMenu3.add(jMenu13);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\about_3697.png")); // NOI18N
        jMenu4.setText("Sobre");
        jMenuBar1.add(jMenu4);

        jFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu14.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\Archivos_25593.png")); // NOI18N
        jMenu14.setText("Arquivos");

        jMenu15.setText("Sair");
        jMenu14.add(jMenu15);

        jMenuBar2.add(jMenu14);

        jMenu16.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\bootloader_users_person_people_6080.png")); // NOI18N
        jMenu16.setText("Usuários");

        jMenu17.setText("Cadastrar");
        jMenu16.add(jMenu17);

        jMenu18.setText("Alterar");
        jMenu16.add(jMenu18);

        jMenu19.setText("Excluir");
        jMenu16.add(jMenu19);

        jMenu20.setText("Pesquisar");
        jMenu16.add(jMenu20);

        jMenuBar2.add(jMenu16);

        jMenu21.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\userrating-115845_115824.png")); // NOI18N
        jMenu21.setText("Clientes");

        jMenu22.setText("Cadastrar");
        jMenu21.add(jMenu22);

        jMenu23.setText("Alterar");
        jMenu21.add(jMenu23);

        jMenu24.setText("Excluir");
        jMenu21.add(jMenu24);

        jMenu25.setText("Pesquisar");
        jMenu21.add(jMenu25);

        jMenuBar2.add(jMenu21);

        jMenu26.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\about_3697.png")); // NOI18N
        jMenu26.setText("Sobre");
        jMenuBar2.add(jMenu26);

        jFrame2.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        jFrame3.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu27.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\Archivos_25593.png")); // NOI18N
        jMenu27.setText("Arquivos");

        jMenu28.setText("Sair");
        jMenu27.add(jMenu28);

        jMenuBar3.add(jMenu27);

        jMenu29.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\bootloader_users_person_people_6080.png")); // NOI18N
        jMenu29.setText("Usuários");

        jMenu30.setText("Cadastrar");
        jMenu29.add(jMenu30);

        jMenu31.setText("Alterar");
        jMenu29.add(jMenu31);

        jMenu32.setText("Excluir");
        jMenu29.add(jMenu32);

        jMenu33.setText("Pesquisar");
        jMenu29.add(jMenu33);

        jMenuBar3.add(jMenu29);

        jMenu34.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\userrating-115845_115824.png")); // NOI18N
        jMenu34.setText("Clientes");

        jMenu35.setText("Cadastrar");
        jMenu34.add(jMenu35);

        jMenu36.setText("Alterar");
        jMenu34.add(jMenu36);

        jMenu37.setText("Excluir");
        jMenu34.add(jMenu37);

        jMenu38.setText("Pesquisar");
        jMenu34.add(jMenu38);

        jMenuBar3.add(jMenu34);

        jMenu39.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\about_3697.png")); // NOI18N
        jMenu39.setText("Sobre");
        jMenuBar3.add(jMenu39);

        jFrame3.setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout Desktop1Layout = new javax.swing.GroupLayout(Desktop1);
        Desktop1.setLayout(Desktop1Layout);
        Desktop1Layout.setHorizontalGroup(
            Desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        Desktop1Layout.setVerticalGroup(
            Desktop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        jMenu40.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\Archivos_25593.png")); // NOI18N
        jMenu40.setText("Arquivos");

        jMenu44.setText("Sair");
        jMenu40.add(jMenu44);

        jMenuBar4.add(jMenu40);

        jMenu41.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\bootloader_users_person_people_6080.png")); // NOI18N
        jMenu41.setText("Usuários");
        jMenu41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu41ActionPerformed(evt);
            }
        });

        fCadastrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\353430-checkbox-edit-pen-pencil_107516.png")); // NOI18N
        fCadastrar.setText("Cadastrar");
        jMenu41.add(fCadastrar);

        jMenu46.setText("Alterar");
        jMenu41.add(jMenu46);

        jMenu47.setText("Excluir");
        jMenu41.add(jMenu47);

        jMenu48.setText("Pesquisar");
        jMenu41.add(jMenu48);

        jMenuBar4.add(jMenu41);

        jMenu42.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\userrating-115845_115824.png")); // NOI18N
        jMenu42.setText("Clientes");

        jMenu49.setText("Cadastrar");
        jMenu42.add(jMenu49);

        jMenu50.setText("Alterar");
        jMenu42.add(jMenu50);

        jMenu51.setText("Excluir");
        jMenu42.add(jMenu51);

        jMenu52.setText("Pesquisar");
        jMenu42.add(jMenu52);

        jMenuBar4.add(jMenu42);

        jMenu43.setIcon(new javax.swing.ImageIcon("C:\\Users\\lerinha\\Downloads\\about_3697.png")); // NOI18N
        jMenu43.setText("Sobre");
        jMenuBar4.add(jMenu43);

        setJMenuBar(jMenuBar4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu41ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalSDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalSDI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop1;
    private javax.swing.JMenu fCadastrar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenu jMenu25;
    private javax.swing.JMenu jMenu26;
    private javax.swing.JMenu jMenu27;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu30;
    private javax.swing.JMenu jMenu31;
    private javax.swing.JMenu jMenu32;
    private javax.swing.JMenu jMenu33;
    private javax.swing.JMenu jMenu34;
    private javax.swing.JMenu jMenu35;
    private javax.swing.JMenu jMenu36;
    private javax.swing.JMenu jMenu37;
    private javax.swing.JMenu jMenu38;
    private javax.swing.JMenu jMenu39;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu40;
    private javax.swing.JMenu jMenu41;
    private javax.swing.JMenu jMenu42;
    private javax.swing.JMenu jMenu43;
    private javax.swing.JMenu jMenu44;
    private javax.swing.JMenu jMenu46;
    private javax.swing.JMenu jMenu47;
    private javax.swing.JMenu jMenu48;
    private javax.swing.JMenu jMenu49;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu50;
    private javax.swing.JMenu jMenu51;
    private javax.swing.JMenu jMenu52;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    // End of variables declaration//GEN-END:variables
}
